[package]
name = "communication_grandchild_with_grandparent"
version = "0.0.1"
authors = ["Marcel Ibes <mibes@mibesco.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
